<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">copy</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoNCnRyeSB7DQogICAg
U3RyaW5nIHNvdXJjZSA9IElEYXRhSGVscGVyLmdldChjdXJzb3IsICIkZmlsZS5zb3VyY2UiLCBT
dHJpbmcuY2xhc3MpOw0KICAgIFN0cmluZyB0YXJnZXQgPSBJRGF0YUhlbHBlci5nZXQoY3Vyc29y
LCAiJGZpbGUudGFyZ2V0IiwgU3RyaW5nLmNsYXNzKTsNCiAgICBTdHJpbmcgbW9kZSA9IElEYXRh
SGVscGVyLmZpcnN0T3JEZWZhdWx0KGN1cnNvciwgU3RyaW5nLmNsYXNzLCAiY3JlYXRlIiwgIiRm
aWxlLm1vZGUiLCAiJG1vZGUiKTsNCg0KICAgIGlmIChtb2RlLmVxdWFsc0lnbm9yZUNhc2UoImNy
ZWF0ZSIpICYmIEZpbGVIZWxwZXIuZXhpc3RzKHRhcmdldCkpIHsNCiAgICAgICAgdGhyb3cgbmV3
IElPRXhjZXB0aW9uKCJmaWxlIGFscmVhZHkgZXhpc3RzIGFuZCB3aWxsIG5vdCBiZSBvdmVyd3Jp
dHRlbiBvciBhcHBlbmRlZCB0bzogIiArIHRhcmdldCk7DQogICAgfSBlbHNlIHsNCiAgICAgICAg
RmlsZUhlbHBlci5jb3B5KHNvdXJjZSwgdGFyZ2V0LCBtb2RlLmVxdWFsc0lnbm9yZUNhc2UoImFw
cGVuZCIpKTsNCiAgICB9DQp9IGNhdGNoKElPRXhjZXB0aW9uIGV4KSB7DQogICAgRXhjZXB0aW9u
SGVscGVyLnJhaXNlKGV4KTsNCn0gZmluYWxseSB7DQogICAgY3Vyc29yLmRlc3Ryb3koKTsNCn0=
</value>
</Values>
